### ISSUE TITLE
Edit triton guides on gpu  to include partition (-p) when initiating interactive session

### ISSUE THREAD

**Issue by yashasvi-ranawat** [AaltoScienceIT/scicomp-docs#26]
$ sinteractive -t 1:00:00 --gres=gpu:teslap100:1
        sbatch: error: Batch job submission failed: Requested node configuration is not available

However when partition is specified, it runs the interactive session well.

        $ sinteractive -t 1:00:00 -p gpushort --gres=gpu:teslap100:1
        Waiting for JOBID xxxxxxxx to start

**Comment by rkdarst** [comment]
Somehow I missed this... but at some poitn I updated the guide anyway.  But... now I have fixed `job_submit.lua` so that `sinteractive` with `--gres=gpu` automatically does go to the gpu partitions!

Thanks for the report!
